version: "3.9"
services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin # Just for demo purposes
      MINIO_ROOT_PASSWORD: password # Just for demo purposes
      MINIO_DOMAIN: minio
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
          - ./minio-data:/data
    command: [ "server", "/data", "--console-address", ":9001" ]

  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    entrypoint: >
      /bin/sh -c "
        until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
        /usr/bin/mc mb minio/github;
        /usr/bin/mc anonymous set public minio/github;
        tail -f /dev/null
      "
